urls.py
from django.conf.urls import url
from . import views

app_name = 'food'
urlpatterns = [
	
	url(r'^$', views.index, name='index'),
	url(r'^details/(?P<f_name>)/', views.details, name='details'),
	url(r'^details/(.+)/', views.details, name='details'),
	url(r'^details/',views.details, name='details'),
	url(r'^submit/(?P<pk>\d+)/', views.submit, name='submit'),
	url(r'^showAll/$', views.showAll, name='showAll'),
	url(r'^delete/$', views.delete, name='delete'),






	#url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
        #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    	#url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	

#	url(r'^$', include('food.urls')),
   	#url(r'^admin/', admin.site.urls),
	
	#url(r'^$', views.IndexView.as_view(), name='index'),
      #url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
        #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
        #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
] 

models.py
from django.db import models

from django.utils import timezone 
import datetime


#from django.utils.encoding import python_2_unicode_compatible


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    #def__str__(self)
      #  return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
	#def __str__(self):
       # return self.choice_te

class RecipeInfo(models.Model):
	recipe_name = models.CharField(max_length=100)
	recipe_content = models.CharField(max_length=200)

	def __str__(self):
		return (self.recipe_name + " " + self.recipe_content)




#class Question(models.Model):
#	def was_published_recently(self):
#		return self.pub_date >=timezone.now() - datetime.timedelta(days=1)
#
#	def__str__(self)
#	return self.choice_text
#	question_text = models.CharField(max_length=200)
#	pub_date = models.DateTimeField('date published')
#
#class Choice(models.Model):
#	question = models.ForeignKey(Question, on_delete=models.CASCADE)
#	choice_text = models.CharField(max_length=200)
#	vote = models.IntegerField(default=0)

# Create your models here.

templates/food/delete.html
<h4>Successfully Deleted.</h4>
<form action={% url 'food:index' %}>
	<input type="submit" value="Back" />
</form>

templates/food/detail.html
{% load static %}

{% if records %}
<div class="post">
<h4>Recipe:</h4>

<table>
  <tr>
    <th>Recipe Name</th>
    <th>Recipe Content</th>
  </tr>

    {% for item in records %}
  <tr>
    <td>{{ item.recipe_name }}</td>
    <td>{{ item.recipe_content }}</td>
  </tr>
    {% endfor %}
</table>
<form action={% url 'food:index' %}>
        <input type="submit" value="Back" />
</form>
</div>
{% else %}
        <p>No data.</p>
{% endif %}

templates/food/details.html
<div class="post">
<h4>Successfully Added.</h4>

<table style="border: 1px solid black;">
  <tr>
    <th>Recipe Name</th>
    <th>Recipe Content</th>
  </tr>
  <tr>
    <td>{{ post.recipe_name }}</td>
    <td>{{ post.recipe_content }}</td>
  </tr>
</table>
<form action={% url 'food:index' %}>
        <input type="submit" value="Back" />
</form>
</div>

templates/food/index.html
<h2>Recipes</h2>
<h4>Submit a Recipe:</h4>
<form method="POST" class="post-form">{% csrf_token %}
	{{form.as_p}}
	<button type="submit" name="submit" class="save btn btn-default">Submit</button>
</form>
<h4>Find a Recipe:</h4>
<form method="POST">{% csrf_token %}
	{{ findform.as_p }}
	<input type="submit" name="find" value="Find Recipe"/>
</form>
<h4>Delete Recipe:</h4>
<form method="POST">{% csrf_token %}
	{{ deleteform.as_p }}
	<input type="submit" name="delete" value="Delete Recipe"/>
</form>
<h4>View All Recipes:</h4>
<form action={% url 'food:showAll' %}>
	<input type="submit" value="Show All" />
</form>

templates/food/showAll.html
{% load static %}

{% if groups %}
<form action={% url 'food:index' %}>
        <input type="submit" value="Back" />
</form>
    <h4>Current Recipes:</h4>
    <table>
  <tr>
    <th>Recipe Name</th>
    <th>Recipe Content</th>
  </tr>
        {% for item in groups %}
  <tr>
    <td>{{ item.recipe_name }}</td>
    <td>{{ item.recipe_content }}</td>
  </tr>
        {% endfor %}
    </table>
{% else %}
        <p>No data.</p>
{% endif %}

templates/food/tempdetail.html
{{ question }}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'food:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

templates/food/tempresult.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'food:detail' question.id %}">Vote again?</a>